### ISSUE TITLE
Update ReadMe File for V1.1

### ISSUE THREAD

**Issue by AAlghrairy** [AY2122S2-CS2103T-W14-2/tp#14]
1. Include the UI mock-up of intended final product
2. Update contents to match own project,
3. Add GitHub Actions build status badge. ![image](https://user-images.githubusercontent.com/77106335/155319922-51dbf56c-67d4-4eed-8283-a571f4177bc9.png)
4. Acknowledge the original source of the code e.g.,
`This project is based on the AddressBook-Level3 project created by the [SE-EDU initiative](https://se-education.org).`

**Comment by simjunheng** [comment]
@juayhee Feel free to close this issue once you have updated the readme file.
