### ISSUE TITLE
[PE-D] Strategy planning does not save

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-2/tp#176]
Strategy planning does not save after exiting the program and it is not indicated anywhere in the UG that this is the case. I think it would be safe to assume that it would be saved since everything else in the address book is saved on exit.

Could be an annoyance for someone that had worked hard to place all the players down, or for someone that wants to stop and continue working on it later.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: KeithCZW/ped#9

**Comment by Rye-Catcher** [comment]
Duplicated with #192
