### ISSUE TITLE
[PE-D] load-court basketball does not work as per guided in the user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W14-2/tp#181]
load-court basketball

![Screenshot 2022-04-01 at 3.15.47 PM.png](https://raw.githubusercontent.com/michaelseyo/ped/main/files/de38f08c-d7a7-4b6a-91f8-2bc9fcaa14bd.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: michaelseyo/ped#20

**Comment by simjunheng** [comment]
Duplicated issue with #196

**Comment by AAlghrairy** [comment]
> Duplicated issue with #196

I don't think this is a duplicate. It seems to be a misunderstanding of how the load-court works, as the basketball image is not included with the jar.
