### ISSUE TITLE
[PE-D] Task Object accepts a task with a end time earlier than its start time

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-2/tp#202]
When adding a task, the command accepts a task with a end time earlier than its start time, which does not make sense.

![image.png](https://raw.githubusercontent.com/alexteo98/ped/main/files/2c8d8464-1aa9-43f5-aeb8-a32565bffebd.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: alexteo98/ped#9

**Comment by prgJ** [comment]
Duplicate with #158
