### ISSUE TITLE
Improve Team Developer Guide

### ISSUE THREAD

**Issue by simjunheng** [AY2122S2-CS2103T-W14-2/tp#222]
1. Refer to the project collaboration notes for more details.
2. https://docs.google.com/document/d/1Dqr7jzMVZovSkf_vFGNBA7gyR892VFi_DE896cJoqeM/edit

**Comment by AAlghrairy** [comment]
Add the purpose of the guide, the target audience and include clear and complete information about how to use the guide. [JH]
Include clear and complete information on how to get started (e.g. installation instructions, operating systems, parts of the GUI, tutorial on how to use CLI) [Abdul]
Add proper signposting in the features section [Juay Hee]
Add proper signposting in the command summary section [XiaoTeng]
Amend UG to ensure that it is coherent [Pragya]
